name: babyai
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.10
    - pytorch=1.12
    - numpy
    - blosc
    - pip
    - pip:
        - git+https://github.com/pseudo-rnd-thoughts/gym.git@fixed-env-checker
        - scikit-build
        - gym[other]
